import type { AssetSignalSeed, MarketSummary } from "@/types";

export const marketSummary: MarketSummary = {
  indices: [
    { name: "S&P 500", ticker: "SPX", level: 5348, changePct: 0.6, trend: "up" },
    { name: "Nasdaq 100", ticker: "NDX", level: 18842, changePct: 1, trend: "up" },
    { name: "Russell 2000", ticker: "IWM", level: 208, changePct: 0.2, trend: "flat" },
    { name: "Gold", ticker: "XAU", level: 2191, changePct: 0.5, trend: "up" },
    { name: "WTI", ticker: "CL", level: 80.6, changePct: 0.7, trend: "up" },
  ],
  majorIndexTrend: "bullish",
  usdTrend: "down",
  bondYieldDirection: "up",
  goldBehavior: "stable",
  oilBehavior: "rising",
  volatilityState: "elevated",
  vix: 17.8,
  breadthPct: 59,
  macroEventFlags: {
    inflationRisk: true,
    centralBankRisk: true,
    growthRisk: true,
    liquidityRisk: false,
  },
  geopoliticalSeverity: "High",
};

type AssetSpec = Omit<
  AssetSignalSeed,
  "technicalSetup" | "technicalInsight" | "executionPlan" | "regimeFitText"
> & {
  pattern: string;
  catalystWindow: string;
};

function round(value: number) {
  return Number(value.toFixed(1));
}

function buildRange(price: number, percent: number) {
  const lower = round(price * (1 - percent));
  const upper = round(price * (1 + percent));
  return `${lower}-${upper}`;
}

function buildAsset(spec: AssetSpec): AssetSignalSeed {
  const support = round(spec.price * (1 - spec.stopDistancePct / 100));
  const resistance = round(spec.price * 1.03);

  return {
    ...spec,
    technicalSetup: {
      timeframe: "Daily",
      pattern: spec.pattern,
      trigger: `Hold above ${round(spec.price * 0.995)} and push through ${resistance}`,
      invalidation: `Close below ${support}`,
      support,
      resistance,
    },
    technicalInsight: {
      setupExplanation: `${spec.name} is being tracked as a ${spec.pattern.toLowerCase()} setup with a catalyst window around ${spec.catalystWindow}.`,
      confirmationSignals: [
        `Price holds above ${round(spec.price * 0.995)}`,
        "Breadth remains supportive",
        "Macro event reaction does not break relative strength",
      ],
    },
    executionPlan: {
      entryZone: buildRange(spec.price, 0.012),
      addZone: buildRange(spec.price * 1.03, 0.01),
      stop: `${support}`,
      targetOne: `${round(spec.price * 1.06)}`,
      targetTwo: `${round(spec.price * 1.11)}`,
      timeframe: "2-8 weeks",
      steps: [
        "Wait for confirmation through the trigger level.",
        "Add only if breadth and macro reaction remain aligned.",
        "Trim into target one and trail the balance if leadership persists.",
      ],
    },
    regimeFitText: `This asset fits best when the tape stays selective, event-aware, and focused on high-quality leadership rather than indiscriminate beta.`,
  };
}

export const assetUniverse: AssetSignalSeed[] = [
  buildAsset({
    ticker: "MSFT",
    name: "Microsoft",
    assetClass: "Equity",
    region: "United States",
    sector: "Software",
    currency: "USD",
    price: 427,
    changePct: 0.8,
    themes: ["AI Infrastructure", "Quality Growth", "Cloud"],
    allocationBucket: "core",
    momentum: 88,
    trendStructure: 87,
    relativeStrength: 85,
    volatilityQuality: 78,
    valuationSanity: 68,
    liquidity: 97,
    catalystStrength: 82,
    averageVolumeLabel: "Very High",
    catalyst: "Cloud capex and AI monetization updates",
    direction: "LONG",
    stopDistancePct: 5.2,
    conviction: 86,
    shortThesis: "High-quality AI leadership remains a core allocation as long as rates do not reprice sharply higher.",
    pattern: "Shelf breakout",
    catalystWindow: "the next cloud capex read-through",
  }),
  buildAsset({
    ticker: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    region: "United States",
    sector: "Semiconductors",
    currency: "USD",
    price: 968,
    changePct: 1.9,
    themes: ["AI Infrastructure", "Semiconductor Leadership", "US Growth"],
    allocationBucket: "tactical",
    momentum: 96,
    trendStructure: 92,
    relativeStrength: 95,
    volatilityQuality: 70,
    valuationSanity: 56,
    liquidity: 99,
    catalystStrength: 92,
    averageVolumeLabel: "Very High",
    catalyst: "AI server demand and cloud capex checks",
    direction: "LONG",
    stopDistancePct: 5.5,
    conviction: 90,
    shortThesis: "The cleanest high-conviction leadership name while AI capex remains a top market narrative.",
    pattern: "High-tight flag",
    catalystWindow: "this week’s cloud commentary",
  }),
  buildAsset({
    ticker: "AMZN",
    name: "Amazon",
    assetClass: "Equity",
    region: "United States",
    sector: "Internet",
    currency: "USD",
    price: 188,
    changePct: 0.7,
    themes: ["Consumer Cloud", "AI Infrastructure", "US Growth"],
    allocationBucket: "core",
    momentum: 80,
    trendStructure: 83,
    relativeStrength: 79,
    volatilityQuality: 74,
    valuationSanity: 62,
    liquidity: 94,
    catalystStrength: 78,
    averageVolumeLabel: "High",
    catalyst: "AWS demand and margin expansion commentary",
    direction: "LONG",
    stopDistancePct: 5,
    conviction: 78,
    shortThesis: "A cleaner large-cap expression of cloud and consumer resilience than lower-quality beta.",
    pattern: "Ascending channel",
    catalystWindow: "the next cloud demand update",
  }),
  buildAsset({
    ticker: "META",
    name: "Meta Platforms",
    assetClass: "Equity",
    region: "United States",
    sector: "Internet",
    currency: "USD",
    price: 522,
    changePct: 0.9,
    themes: ["Advertising Recovery", "AI Enablement", "Quality Growth"],
    allocationBucket: "core",
    momentum: 84,
    trendStructure: 82,
    relativeStrength: 80,
    volatilityQuality: 77,
    valuationSanity: 66,
    liquidity: 93,
    catalystStrength: 77,
    averageVolumeLabel: "High",
    catalyst: "Ad pricing and capex discipline",
    direction: "LONG",
    stopDistancePct: 4.9,
    conviction: 79,
    shortThesis: "Meta remains a high-quality platform compounding story with a cleaner risk profile than speculative AI beta.",
    pattern: "Base-on-base",
    catalystWindow: "next ad channel checks",
  }),
  buildAsset({
    ticker: "GOOGL",
    name: "Alphabet",
    assetClass: "Equity",
    region: "United States",
    sector: "Internet",
    currency: "USD",
    price: 164,
    changePct: 0.5,
    themes: ["AI Enablement", "Digital Ads", "Cash Flow"],
    allocationBucket: "core",
    momentum: 77,
    trendStructure: 79,
    relativeStrength: 74,
    volatilityQuality: 80,
    valuationSanity: 72,
    liquidity: 94,
    catalystStrength: 70,
    averageVolumeLabel: "High",
    catalyst: "Search monetization and Gemini adoption",
    direction: "LONG",
    stopDistancePct: 4.8,
    conviction: 74,
    shortThesis: "Alphabet remains an efficient quality compounder with a more balanced valuation than hotter mega-cap peers.",
    pattern: "Tight consolidation",
    catalystWindow: "AI search product updates",
  }),
  buildAsset({
    ticker: "JPM",
    name: "JPMorgan Chase",
    assetClass: "Equity",
    region: "United States",
    sector: "Financials",
    currency: "USD",
    price: 203,
    changePct: 0.4,
    themes: ["Quality Financials", "Higher Rates", "US Large Cap"],
    allocationBucket: "core",
    momentum: 72,
    trendStructure: 77,
    relativeStrength: 70,
    volatilityQuality: 82,
    valuationSanity: 75,
    liquidity: 92,
    catalystStrength: 69,
    averageVolumeLabel: "High",
    catalyst: "NIM stability and credit quality",
    direction: "LONG",
    stopDistancePct: 4.5,
    conviction: 71,
    shortThesis: "JPM offers quality financial exposure that can hold up if higher rates persist without a recession break.",
    pattern: "Trend continuation shelf",
    catalystWindow: "bank commentary and rates reaction",
  }),
  buildAsset({
    ticker: "XOM",
    name: "Exxon Mobil",
    assetClass: "Equity",
    region: "United States",
    sector: "Energy",
    currency: "USD",
    price: 118,
    changePct: 0.8,
    themes: ["Energy Cash Flow", "Inflation Protection", "Value"],
    allocationBucket: "core",
    momentum: 69,
    trendStructure: 74,
    relativeStrength: 67,
    volatilityQuality: 83,
    valuationSanity: 78,
    liquidity: 91,
    catalystStrength: 73,
    averageVolumeLabel: "High",
    catalyst: "Oil discipline and cash return cadence",
    direction: "LONG",
    stopDistancePct: 4.7,
    conviction: 72,
    shortThesis: "A steady energy sleeve that helps diversify growth-heavy exposure and hedge inflation surprises.",
    pattern: "Range breakout attempt",
    catalystWindow: "OPEC+ compliance headlines",
  }),
  buildAsset({
    ticker: "CAT",
    name: "Caterpillar",
    assetClass: "Equity",
    region: "United States",
    sector: "Industrials",
    currency: "USD",
    price: 355,
    changePct: 0.6,
    themes: ["Infrastructure", "Industrial Capex", "Localization"],
    allocationBucket: "core",
    momentum: 75,
    trendStructure: 79,
    relativeStrength: 73,
    volatilityQuality: 76,
    valuationSanity: 70,
    liquidity: 88,
    catalystStrength: 71,
    averageVolumeLabel: "High",
    catalyst: "Infrastructure and capex demand checks",
    direction: "LONG",
    stopDistancePct: 4.6,
    conviction: 73,
    shortThesis: "A cleaner single-name cyclical tied to infrastructure and domestic capex than weaker commodity-sensitive names.",
    pattern: "Ascending base",
    catalystWindow: "upcoming industrial order flow",
  }),
  buildAsset({
    ticker: "LLY",
    name: "Eli Lilly",
    assetClass: "Equity",
    region: "United States",
    sector: "Health Care",
    currency: "USD",
    price: 782,
    changePct: 0.3,
    themes: ["Health Care Leadership", "Defensive Growth", "Quality"],
    allocationBucket: "core",
    momentum: 71,
    trendStructure: 79,
    relativeStrength: 76,
    volatilityQuality: 82,
    valuationSanity: 54,
    liquidity: 88,
    catalystStrength: 75,
    averageVolumeLabel: "High",
    catalyst: "Obesity pipeline and earnings revision flow",
    direction: "LONG",
    stopDistancePct: 4.4,
    conviction: 76,
    shortThesis: "Health care leadership provides cleaner defensive growth if the tape rotates out of crowded cyclicals.",
    pattern: "Tight leader coil",
    catalystWindow: "next pharma pipeline updates",
  }),
  buildAsset({
    ticker: "UBER",
    name: "Uber",
    assetClass: "Equity",
    region: "United States",
    sector: "Internet",
    currency: "USD",
    price: 83,
    changePct: 1.1,
    themes: ["Platform Efficiency", "Mobility", "Cash Flow Turn"],
    allocationBucket: "tactical",
    momentum: 79,
    trendStructure: 76,
    relativeStrength: 81,
    volatilityQuality: 72,
    valuationSanity: 67,
    liquidity: 89,
    catalystStrength: 74,
    averageVolumeLabel: "High",
    catalyst: "Take-rate durability and margins",
    direction: "LONG",
    stopDistancePct: 5.4,
    conviction: 75,
    shortThesis: "Uber remains a strong execution story with less direct rates sensitivity than speculative platform peers.",
    pattern: "Momentum shelf",
    catalystWindow: "next unit economics update",
  }),
  buildAsset({
    ticker: "COST",
    name: "Costco",
    assetClass: "Equity",
    region: "United States",
    sector: "Consumer Staples",
    currency: "USD",
    price: 731,
    changePct: 0.4,
    themes: ["Defensive Quality", "Consumer Resilience", "Membership"],
    allocationBucket: "core",
    momentum: 68,
    trendStructure: 74,
    relativeStrength: 72,
    volatilityQuality: 84,
    valuationSanity: 58,
    liquidity: 90,
    catalystStrength: 66,
    averageVolumeLabel: "High",
    catalyst: "Traffic and renewal rates",
    direction: "LONG",
    stopDistancePct: 4.2,
    conviction: 70,
    shortThesis: "Costco offers defensive quality if growth anxiety rises without abandoning equity exposure altogether.",
    pattern: "High-level pullback",
    catalystWindow: "monthly sales update",
  }),
  buildAsset({
    ticker: "TSLA",
    name: "Tesla",
    assetClass: "Equity",
    region: "United States",
    sector: "Autos",
    currency: "USD",
    price: 189,
    changePct: -1.1,
    themes: ["EV Transition", "Rate Sensitive Growth", "China Exposure"],
    allocationBucket: "tactical",
    momentum: 40,
    trendStructure: 38,
    relativeStrength: 35,
    volatilityQuality: 40,
    valuationSanity: 45,
    liquidity: 97,
    catalystStrength: 56,
    averageVolumeLabel: "Very High",
    catalyst: "Delivery data and pricing commentary",
    direction: "LONG",
    stopDistancePct: 5,
    conviction: 44,
    shortThesis: "Liquidity keeps Tesla on the board, but the signal stack is too weak for priority capital right now.",
    pattern: "Broken base",
    catalystWindow: "delivery and pricing headlines",
  }),
  buildAsset({
    ticker: "XLK",
    name: "Technology Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Technology",
    currency: "USD",
    price: 224,
    changePct: 0.8,
    themes: ["Large Cap Tech", "Quality Growth", "AI Infrastructure"],
    allocationBucket: "core",
    momentum: 82,
    trendStructure: 84,
    relativeStrength: 82,
    volatilityQuality: 79,
    valuationSanity: 64,
    liquidity: 96,
    catalystStrength: 78,
    averageVolumeLabel: "High",
    catalyst: "Mega-cap breadth and earnings revisions",
    direction: "LONG",
    stopDistancePct: 4.6,
    conviction: 80,
    shortThesis: "The clean ETF expression of dominant US tech leadership with lower idiosyncratic gap risk.",
    pattern: "Trend channel",
    catalystWindow: "the next mega-cap catalyst cluster",
  }),
  buildAsset({
    ticker: "XLI",
    name: "Industrial Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Industrials",
    currency: "USD",
    price: 131,
    changePct: 0.7,
    themes: ["Global Cyclicals", "Infrastructure", "Localization"],
    allocationBucket: "core",
    momentum: 81,
    trendStructure: 84,
    relativeStrength: 77,
    volatilityQuality: 83,
    valuationSanity: 72,
    liquidity: 93,
    catalystStrength: 76,
    averageVolumeLabel: "High",
    catalyst: "PMI stabilization and reshoring spend",
    direction: "LONG",
    stopDistancePct: 4.2,
    conviction: 81,
    shortThesis: "A diversified cyclical breadth expression with cleaner valuation and risk than crowded single-name growth.",
    pattern: "Ascending base",
    catalystWindow: "this month’s PMI and capex data",
  }),
  buildAsset({
    ticker: "XLE",
    name: "Energy Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Energy",
    currency: "USD",
    price: 121,
    changePct: 0.6,
    themes: ["Energy Cash Flow", "Inflation Protection", "Commodity Beta"],
    allocationBucket: "core",
    momentum: 67,
    trendStructure: 72,
    relativeStrength: 69,
    volatilityQuality: 82,
    valuationSanity: 77,
    liquidity: 92,
    catalystStrength: 74,
    averageVolumeLabel: "High",
    catalyst: "Oil price response to geopolitics",
    direction: "LONG",
    stopDistancePct: 4.8,
    conviction: 72,
    shortThesis: "Energy remains a useful inflation and geopolitical sleeve if crude maintains a risk premium.",
    pattern: "Compression under highs",
    catalystWindow: "OPEC and geopolitical flow",
  }),
  buildAsset({
    ticker: "XLF",
    name: "Financial Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Financials",
    currency: "USD",
    price: 43.5,
    changePct: 0.3,
    themes: ["Financials", "Value", "Higher Rates"],
    allocationBucket: "core",
    momentum: 65,
    trendStructure: 69,
    relativeStrength: 66,
    volatilityQuality: 81,
    valuationSanity: 76,
    liquidity: 94,
    catalystStrength: 63,
    averageVolumeLabel: "High",
    catalyst: "Rates and credit stability",
    direction: "LONG",
    stopDistancePct: 4.3,
    conviction: 66,
    shortThesis: "A broad financials sleeve works if higher rates persist without a growth break or credit scare.",
    pattern: "Range hold",
    catalystWindow: "auction and bank commentary",
  }),
  buildAsset({
    ticker: "XLP",
    name: "Consumer Staples Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Consumer Staples",
    currency: "USD",
    price: 78,
    changePct: 0.4,
    themes: ["Defensive Quality", "Staples", "Lower Beta"],
    allocationBucket: "hedge",
    momentum: 58,
    trendStructure: 67,
    relativeStrength: 63,
    volatilityQuality: 86,
    valuationSanity: 69,
    liquidity: 87,
    catalystStrength: 55,
    averageVolumeLabel: "High",
    catalyst: "Consumer stress and defensive rotation",
    direction: "LONG",
    stopDistancePct: 3.8,
    conviction: 62,
    shortThesis: "A defensive sleeve that becomes more useful if growth anxiety broadens without a hard risk-off break.",
    pattern: "Defensive base",
    catalystWindow: "next consumer demand prints",
  }),
  buildAsset({
    ticker: "XLV",
    name: "Health Care Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Health Care",
    currency: "USD",
    price: 141,
    changePct: 0.5,
    themes: ["Defensive Growth", "Quality", "Earnings Stability"],
    allocationBucket: "core",
    momentum: 66,
    trendStructure: 73,
    relativeStrength: 71,
    volatilityQuality: 84,
    valuationSanity: 71,
    liquidity: 89,
    catalystStrength: 62,
    averageVolumeLabel: "High",
    catalyst: "Defensive rotation and quality flows",
    direction: "LONG",
    stopDistancePct: 4,
    conviction: 68,
    shortThesis: "Health care is a cleaner defensive-growth sleeve than consumer cyclicals when the tape gets less forgiving.",
    pattern: "Range breakout watch",
    catalystWindow: "quality rotation",
  }),
  buildAsset({
    ticker: "SMH",
    name: "VanEck Semiconductor ETF",
    assetClass: "ETF",
    region: "United States",
    sector: "Semiconductors",
    currency: "USD",
    price: 251,
    changePct: 1.3,
    themes: ["Semiconductor Leadership", "AI Infrastructure", "US Growth"],
    allocationBucket: "tactical",
    momentum: 89,
    trendStructure: 86,
    relativeStrength: 90,
    volatilityQuality: 69,
    valuationSanity: 58,
    liquidity: 91,
    catalystStrength: 86,
    averageVolumeLabel: "High",
    catalyst: "Broad semi participation and AI capex",
    direction: "LONG",
    stopDistancePct: 5.4,
    conviction: 84,
    shortThesis: "Broader semiconductor participation is a cleaner way to add AI beta than chasing every single-name spike.",
    pattern: "Momentum shelf",
    catalystWindow: "AI capex and supply-chain updates",
  }),
  buildAsset({
    ticker: "HYG",
    name: "iShares iBoxx $ High Yield Corporate Bond ETF",
    assetClass: "ETF",
    region: "United States",
    sector: "Credit",
    currency: "USD",
    price: 79,
    changePct: 0.2,
    themes: ["Credit Spread Risk", "Carry", "Risk Appetite"],
    allocationBucket: "core",
    momentum: 58,
    trendStructure: 66,
    relativeStrength: 57,
    volatilityQuality: 85,
    valuationSanity: 73,
    liquidity: 87,
    catalystStrength: 52,
    averageVolumeLabel: "High",
    catalyst: "Credit spread stability",
    direction: "LONG",
    stopDistancePct: 3.6,
    conviction: 58,
    shortThesis: "A carry sleeve that works only if growth stress stays contained and credit spreads remain calm.",
    pattern: "Tight carry range",
    catalystWindow: "credit spread checks",
  }),
  buildAsset({
    ticker: "IWM",
    name: "iShares Russell 2000 ETF",
    assetClass: "ETF",
    region: "United States",
    sector: "Small Caps",
    currency: "USD",
    price: 208,
    changePct: 0.1,
    themes: ["Domestic Cyclicals", "Small Caps", "Rate Sensitivity"],
    allocationBucket: "tactical",
    momentum: 55,
    trendStructure: 61,
    relativeStrength: 49,
    volatilityQuality: 65,
    valuationSanity: 72,
    liquidity: 95,
    catalystStrength: 57,
    averageVolumeLabel: "Very High",
    catalyst: "Small-cap breadth and rates relief",
    direction: "LONG",
    stopDistancePct: 5.3,
    conviction: 57,
    shortThesis: "Small caps need rates relief and broader growth confidence before they deserve priority capital.",
    pattern: "Range rotation",
    catalystWindow: "post-Fed rates reaction",
  }),
  buildAsset({
    ticker: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "ETF",
    region: "Global",
    sector: "Precious Metals",
    currency: "USD",
    price: 208,
    changePct: 0.5,
    themes: ["Gold", "Defensive Hedge", "Policy Uncertainty"],
    allocationBucket: "hedge",
    momentum: 69,
    trendStructure: 76,
    relativeStrength: 71,
    volatilityQuality: 88,
    valuationSanity: 66,
    liquidity: 92,
    catalystStrength: 83,
    averageVolumeLabel: "High",
    catalyst: "Fed dots and real-yield response",
    direction: "LONG",
    stopDistancePct: 3,
    conviction: 78,
    shortThesis: "A clean macro hedge when yields, policy communication, and geopolitics all remain active at once.",
    pattern: "Volatility squeeze",
    catalystWindow: "the FOMC and real-yield reaction",
  }),
  buildAsset({
    ticker: "USO",
    name: "United States Oil Fund",
    assetClass: "ETF",
    region: "Global",
    sector: "Energy Proxy",
    currency: "USD",
    price: 79,
    changePct: 0.9,
    themes: ["Energy Proxy", "Commodity Beta", "Inflation Protection"],
    allocationBucket: "tactical",
    momentum: 63,
    trendStructure: 68,
    relativeStrength: 65,
    volatilityQuality: 63,
    valuationSanity: 70,
    liquidity: 83,
    catalystStrength: 81,
    averageVolumeLabel: "High",
    catalyst: "OPEC+ and shipping-route risk",
    direction: "LONG",
    stopDistancePct: 6.2,
    conviction: 68,
    shortThesis: "Pure oil beta only makes sense when geopolitical and inflation pressure stay strong enough to justify tactical commodity exposure.",
    pattern: "Commodity breakout",
    catalystWindow: "OPEC headlines and route disruption flow",
  }),
  buildAsset({
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    assetClass: "ETF",
    region: "United States",
    sector: "Rates",
    currency: "USD",
    price: 96,
    changePct: 0.3,
    themes: ["Duration Hedge", "Policy Uncertainty", "Rate Relief"],
    allocationBucket: "hedge",
    momentum: 54,
    trendStructure: 62,
    relativeStrength: 58,
    volatilityQuality: 86,
    valuationSanity: 74,
    liquidity: 90,
    catalystStrength: 79,
    averageVolumeLabel: "Very High",
    catalyst: "Growth scare and duration hedge demand",
    direction: "LONG",
    stopDistancePct: 4.1,
    conviction: 72,
    shortThesis: "TLT remains one of the cleanest balancing assets if growth softens faster than inflation re-accelerates.",
    pattern: "Bottoming base",
    catalystWindow: "rates and labor data",
  }),
  buildAsset({
    ticker: "IBIT",
    name: "iShares Bitcoin Trust",
    assetClass: "ETF",
    region: "United States",
    sector: "Crypto Proxy",
    currency: "USD",
    price: 41,
    changePct: 2.4,
    themes: ["Crypto Proxy", "Liquidity", "Alternative Beta"],
    allocationBucket: "tactical",
    momentum: 87,
    trendStructure: 79,
    relativeStrength: 88,
    volatilityQuality: 41,
    valuationSanity: 52,
    liquidity: 89,
    catalystStrength: 84,
    averageVolumeLabel: "High",
    catalyst: "ETF flows and global liquidity",
    direction: "LONG",
    stopDistancePct: 8.1,
    conviction: 71,
    shortThesis: "A workable crypto-beta expression only when macro liquidity remains supportive and size stays disciplined.",
    pattern: "High beta continuation",
    catalystWindow: "ETF flow and rates volatility",
  }),
];
