import type { AssetSignalInput, MarketSummary } from "@/types";

export const marketSummary: MarketSummary = {
  indices: [
    { name: "S&P 500", ticker: "SPX", level: 5312, changePct: 0.7, trend: "up" },
    { name: "Nasdaq 100", ticker: "NDX", level: 18642, changePct: 1.1, trend: "up" },
    { name: "MSCI EM", ticker: "EEM", level: 43.8, changePct: -0.3, trend: "flat" },
    { name: "Gold", ticker: "XAU", level: 2184, changePct: 0.4, trend: "up" },
  ],
  usdTrend: "down",
  bondYieldTrend: "flat",
  goldOilSignal: "balanced",
  vix: 15.8,
  breadthPct: 62,
};

export const assetUniverse: AssetSignalInput[] = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    region: "United States",
    sector: "Semiconductors",
    currency: "USD",
    price: 962,
    changePct: 1.8,
    momentum: 96,
    trendStructure: 92,
    relativeStrength: 95,
    volatilityQuality: 72,
    valuationSanity: 58,
    macroFit: 84,
    geopoliticalFit: 63,
    liquidity: 98,
    catalystStrength: 91,
    averageVolumeLabel: "Very High",
    technicalSetup: {
      timeframe: "Daily",
      pattern: "High-tight flag",
      trigger: "Close above 970 with breadth confirmation",
      invalidation: "Daily close back below 914",
      support: 914,
      resistance: 970,
    },
    executionPlan: {
      entryZone: "958-972",
      addZone: "985-1002 on follow-through",
      stop: "913",
      targetOne: "1025",
      targetTwo: "1088",
      timeframe: "2-6 weeks",
    },
    macroReasons: [
      "Falling USD and stable yields extend support for long-duration growth leadership.",
      "AI capex remains a late-cycle growth pocket despite softer aggregate manufacturing data.",
    ],
    geopoliticalReasons: [
      "Export restriction risk remains present but is currently contained within a known headline band.",
      "Supply-chain localization trend continues to benefit high-end compute incumbents.",
    ],
    catalyst: "Cloud capex survey and enterprise AI demand updates",
    direction: "LONG",
    stopDistancePct: 5.1,
    conviction: 89,
  },
  {
    ticker: "XLI",
    name: "Industrial Select Sector SPDR",
    assetClass: "ETF",
    region: "United States",
    sector: "Industrials",
    currency: "USD",
    price: 129,
    changePct: 0.9,
    momentum: 81,
    trendStructure: 84,
    relativeStrength: 77,
    volatilityQuality: 83,
    valuationSanity: 71,
    macroFit: 88,
    geopoliticalFit: 68,
    liquidity: 93,
    catalystStrength: 74,
    averageVolumeLabel: "High",
    technicalSetup: {
      timeframe: "Daily",
      pattern: "Ascending base",
      trigger: "Breakout above 130.2 after macro event risk clears",
      invalidation: "Loss of 124.6 support",
      support: 124.6,
      resistance: 130.2,
    },
    executionPlan: {
      entryZone: "128.5-130.5",
      addZone: "132.0-133.8",
      stop: "124.4",
      targetOne: "136.8",
      targetTwo: "140.5",
      timeframe: "3-8 weeks",
    },
    macroReasons: [
      "Broadening cyclical participation is improving as financial conditions remain supportive.",
      "China stabilization and infrastructure demand create a better earnings backdrop for industrials.",
    ],
    geopoliticalReasons: [
      "Shipping disruptions create pockets of pricing power for selected logistics and industrial names.",
      "Defense and localization spending remain medium-term tailwinds.",
    ],
    catalyst: "Infrastructure procurement and PMI re-acceleration",
    direction: "LONG",
    stopDistancePct: 4,
    conviction: 81,
  },
  {
    ticker: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "ETF",
    region: "Global",
    sector: "Precious Metals",
    currency: "USD",
    price: 207,
    changePct: 0.4,
    momentum: 69,
    trendStructure: 76,
    relativeStrength: 71,
    volatilityQuality: 89,
    valuationSanity: 66,
    macroFit: 79,
    geopoliticalFit: 92,
    liquidity: 91,
    catalystStrength: 82,
    averageVolumeLabel: "High",
    technicalSetup: {
      timeframe: "Daily",
      pattern: "Volatility squeeze above prior range",
      trigger: "Hold above 205 through the Fed and break 209.4",
      invalidation: "Close below 201.8",
      support: 201.8,
      resistance: 209.4,
    },
    executionPlan: {
      entryZone: "206-208",
      addZone: "209.5-211.0",
      stop: "201.6",
      targetOne: "214.8",
      targetTwo: "219.5",
      timeframe: "2-5 weeks",
    },
    macroReasons: [
      "Real-rate sensitivity still favors gold if inflation cools without a growth scare.",
      "It adds balance if the current regime slips from risk-on toward defensive rotation.",
    ],
    geopoliticalReasons: [
      "Middle East shipping tension and election-cycle uncertainty support safe-haven demand.",
      "Central-bank reserve diversification remains a supportive background flow.",
    ],
    catalyst: "Fed dot plot and real yield reaction",
    direction: "LONG",
    stopDistancePct: 2.9,
    conviction: 76,
  },
  {
    ticker: "SMCI",
    name: "Super Micro Computer",
    assetClass: "Equity",
    region: "United States",
    sector: "Servers",
    currency: "USD",
    price: 901,
    changePct: 3.4,
    momentum: 91,
    trendStructure: 74,
    relativeStrength: 88,
    volatilityQuality: 39,
    valuationSanity: 48,
    macroFit: 80,
    geopoliticalFit: 61,
    liquidity: 84,
    catalystStrength: 86,
    averageVolumeLabel: "High",
    technicalSetup: {
      timeframe: "Daily",
      pattern: "High beta continuation",
      trigger: "Only on pullback hold above 860 then reclaim 920",
      invalidation: "Break below 848",
      support: 848,
      resistance: 920,
    },
    executionPlan: {
      entryZone: "886-920",
      addZone: "940-955",
      stop: "847",
      targetOne: "998",
      targetTwo: "1065",
      timeframe: "1-4 weeks",
    },
    macroReasons: [
      "AI infrastructure remains a favored earnings island in a supportive liquidity backdrop.",
      "Leadership persistence works while breadth is improving rather than narrowing.",
    ],
    geopoliticalReasons: [
      "Component concentration keeps headline sensitivity elevated.",
      "Policy risk is manageable but too large for full-size positioning.",
    ],
    catalyst: "Server backlog conversion and margin commentary",
    direction: "LONG",
    stopDistancePct: 6,
    conviction: 72,
  },
  {
    ticker: "TSLA",
    name: "Tesla",
    assetClass: "Equity",
    region: "United States",
    sector: "Autos",
    currency: "USD",
    price: 188,
    changePct: -1.2,
    momentum: 42,
    trendStructure: 38,
    relativeStrength: 34,
    volatilityQuality: 41,
    valuationSanity: 45,
    macroFit: 56,
    geopoliticalFit: 49,
    liquidity: 97,
    catalystStrength: 57,
    averageVolumeLabel: "Very High",
    technicalSetup: {
      timeframe: "Daily",
      pattern: "Broken base",
      trigger: "Avoid long until reclaim of 198 and improving relative strength",
      invalidation: "Fresh breakdown below 182",
      support: 182,
      resistance: 198,
    },
    executionPlan: {
      entryZone: "No trade until structure improves",
      addZone: "N/A",
      stop: "182",
      targetOne: "205",
      targetTwo: "218",
      timeframe: "Wait",
    },
    macroReasons: [
      "Rate-sensitive growth can recover later, but leadership is not yet aligned with current breadth expansion.",
      "Demand elasticity remains under pressure as global pricing normalizes.",
    ],
    geopoliticalReasons: [
      "EV tariff and supply-chain policy uncertainty still clouds the next catalyst window.",
      "China exposure adds headline volatility.",
    ],
    catalyst: "Delivery data and pricing commentary",
    direction: "LONG",
    stopDistancePct: 4.8,
    conviction: 44,
  },
];
