import type { GeopoliticalEvent } from "@/types";

export const geopoliticalEvents: GeopoliticalEvent[] = [
  {
    id: "geo-1",
    title: "Red Sea shipping corridor remains under intermittent threat",
    category: "shipping/logistics disruption",
    region: "Middle East",
    severity: "High",
    severityScore: 84,
    status: "Active",
    affectedRegions: ["Middle East", "Europe", "Global"],
    transmissionChannels: [
      {
        channel: "inflation",
        direction: "higher",
        intensity: 3,
        explanation: "Longer shipping routes keep freight costs and imported goods pressure elevated.",
      },
      {
        channel: "commodities",
        direction: "higher",
        intensity: 2,
        explanation: "Energy and transport-linked commodities keep a risk premium during disruptions.",
      },
      {
        channel: "supplyChain",
        direction: "mixed",
        intensity: 4,
        explanation: "Delivery times and inventory buffers matter more for global manufacturing and retail chains.",
      },
      {
        channel: "riskSentiment",
        direction: "lower",
        intensity: 2,
        explanation: "Headline risk caps aggression in crowded cyclical and consumer names.",
      },
    ],
    beneficiaries: ["Shipping", "Logistics pricing power", "Gold", "Defense"],
    losers: ["European cyclicals", "Import-dependent retail", "Autos"],
    actionSuggestion: "add hedge",
    chips: ["freight risk", "energy premium", "supply chain stress"],
    implication:
      "Keeps freight and energy risk premia elevated; favors resilient quality, select logistics names, and hedge exposure.",
  },
  {
    id: "geo-2",
    title: "US-China semiconductor restrictions broaden",
    category: "sanctions",
    region: "Global",
    severity: "High",
    severityScore: 80,
    status: "Escalation risk",
    affectedRegions: ["United States", "China", "Asia", "Global"],
    transmissionChannels: [
      {
        channel: "growth",
        direction: "lower",
        intensity: 2,
        explanation: "Restrictions weigh on capital spending visibility across exposed supply chains.",
      },
      {
        channel: "earnings",
        direction: "mixed",
        intensity: 4,
        explanation: "Leaders with domestic demand hold up better than firms reliant on restricted end markets.",
      },
      {
        channel: "currencies",
        direction: "mixed",
        intensity: 1,
        explanation: "Asia supply-chain currencies remain headline sensitive during policy escalations.",
      },
      {
        channel: "riskSentiment",
        direction: "lower",
        intensity: 3,
        explanation: "AI leaders remain tradable, but sizing discipline matters because headline gaps stay large.",
      },
    ],
    beneficiaries: ["US localization", "Domestic chip tooling", "Industrial automation"],
    losers: ["China-exposed semis", "High-beta hardware", "Autos with China demand risk"],
    actionSuggestion: "monitor",
    chips: ["export controls", "AI stack", "headline volatility"],
    implication:
      "Creates headline volatility across chips but supports supply-chain localization and domestic capex beneficiaries.",
  },
  {
    id: "geo-3",
    title: "Election volatility rises across major democracies",
    category: "elections/political instability",
    region: "United States",
    severity: "Moderate",
    severityScore: 66,
    status: "Building",
    affectedRegions: ["United States", "Europe"],
    transmissionChannels: [
      {
        channel: "rates",
        direction: "mixed",
        intensity: 2,
        explanation: "Fiscal uncertainty can widen term premium even without an immediate policy move.",
      },
      {
        channel: "currencies",
        direction: "mixed",
        intensity: 2,
        explanation: "FX markets respond quickly when polling shifts imply regime changes in trade or spending.",
      },
      {
        channel: "riskSentiment",
        direction: "lower",
        intensity: 2,
        explanation: "Crowded growth trades face more event-risk premium around policy headlines.",
      },
    ],
    beneficiaries: ["Gold", "Defensives", "Cash"],
    losers: ["Domestic discretionary", "Rate-sensitive growth"],
    actionSuggestion: "monitor",
    chips: ["policy uncertainty", "fiscal drift", "headline volatility"],
    implication:
      "Policy uncertainty stays elevated and argues for cleaner setups, modest hedges, and more patience on crowded longs.",
  },
  {
    id: "geo-4",
    title: "OPEC+ discipline wobble keeps energy shock risk alive",
    category: "energy shock",
    region: "Middle East",
    severity: "Moderate",
    severityScore: 71,
    status: "Monitoring",
    affectedRegions: ["Middle East", "Europe", "Global"],
    transmissionChannels: [
      {
        channel: "inflation",
        direction: "higher",
        intensity: 3,
        explanation: "Oil volatility can re-ignite inflation expectations quickly even if core trends are cooling.",
      },
      {
        channel: "rates",
        direction: "higher",
        intensity: 2,
        explanation: "An energy-led inflation scare would pressure cuts pricing and long-duration multiples.",
      },
      {
        channel: "commodities",
        direction: "higher",
        intensity: 4,
        explanation: "Oil beta and commodity-linked cyclicals remain most sensitive to compliance headlines.",
      },
    ],
    beneficiaries: ["Energy producers", "Commodity exporters", "Gold"],
    losers: ["Airlines", "Consumer cyclicals", "Rate-sensitive growth"],
    actionSuggestion: "avoid sector",
    chips: ["oil beta", "inflation risk", "policy repricing"],
    implication:
      "Affects oil beta and inflation expectations directly, which can quickly tilt the regime away from duration-sensitive leadership.",
  },
  {
    id: "geo-5",
    title: "Tariff rhetoric expands in EV and industrial supply chains",
    category: "tariffs/trade war",
    region: "Global",
    severity: "High",
    severityScore: 78,
    status: "Escalating",
    affectedRegions: ["United States", "Europe", "China"],
    transmissionChannels: [
      {
        channel: "growth",
        direction: "lower",
        intensity: 2,
        explanation: "Trade friction slows confidence and pushes businesses toward defensive inventory planning.",
      },
      {
        channel: "earnings",
        direction: "lower",
        intensity: 3,
        explanation: "Margin pressure rises for firms that cannot pass through higher input or tariff costs.",
      },
      {
        channel: "supplyChain",
        direction: "mixed",
        intensity: 3,
        explanation: "Localization beneficiaries can gain share even while cross-border operators lose efficiency.",
      },
    ],
    beneficiaries: ["Domestic industrials", "Localization capex", "Infrastructure"],
    losers: ["EVs", "China-exposed autos", "Global manufacturers"],
    actionSuggestion: "avoid sector",
    chips: ["trade war", "margin pressure", "localization"],
    implication:
      "Supports localization winners but adds friction to EV, autos, and globally stretched manufacturing chains.",
  },
  {
    id: "geo-6",
    title: "Critical infrastructure cyber probe hits payment and shipping networks",
    category: "cyber/regulatory shock",
    region: "Global",
    severity: "Moderate",
    severityScore: 64,
    status: "Contained but live",
    affectedRegions: ["United States", "Europe", "Global"],
    transmissionChannels: [
      {
        channel: "growth",
        direction: "lower",
        intensity: 1,
        explanation: "Short-lived operational slowdowns can still hit transaction-sensitive businesses.",
      },
      {
        channel: "earnings",
        direction: "mixed",
        intensity: 2,
        explanation: "Cybersecurity spend beneficiaries strengthen while exposed operators see temporary margin drag.",
      },
      {
        channel: "riskSentiment",
        direction: "lower",
        intensity: 1,
        explanation: "Cyber shocks raise the market premium on operational resilience and compliance readiness.",
      },
    ],
    beneficiaries: ["Cybersecurity", "Resilient software", "Cash"],
    losers: ["Payments", "Transport operators", "Low-margin logistics"],
    actionSuggestion: "monitor",
    chips: ["cyber resilience", "regulatory follow-up", "operational risk"],
    implication:
      "Adds a regulatory and resilience premium to software/security names while exposing fragile operators to headline drawdowns.",
  },
  {
    id: "geo-7",
    title: "Border conflict flare-up drives defense and haven demand",
    category: "war/conflict",
    region: "Eastern Europe",
    severity: "Critical",
    severityScore: 90,
    status: "Escalating",
    affectedRegions: ["Eastern Europe", "Europe", "Global"],
    transmissionChannels: [
      {
        channel: "commodities",
        direction: "higher",
        intensity: 3,
        explanation: "Conflict risk lifts energy, grain, and industrial input premia across Europe.",
      },
      {
        channel: "currencies",
        direction: "mixed",
        intensity: 2,
        explanation: "European FX and safe-haven flows respond quickly when military risk escalates.",
      },
      {
        channel: "riskSentiment",
        direction: "lower",
        intensity: 4,
        explanation: "Conflict headlines compress risk appetite and increase the value of defensive hedges.",
      },
    ],
    beneficiaries: ["Defense", "Gold", "USD cash", "Energy"],
    losers: ["European cyclicals", "Travel", "Discretionary"],
    actionSuggestion: "reduce risk",
    chips: ["conflict risk", "safe havens", "Europe exposure"],
    implication:
      "Pushes safe-haven demand higher and caps aggression in Europe-linked cyclicals until the conflict premium fades.",
  },
];
