import type { CatalystItem, MacroEvent, MacroState, SectorHeatmapItem } from "@/types";

export const macroState: MacroState = {
  asOf: "2026-03-14T09:00:00Z",
  inflation: {
    key: "inflation",
    label: "Inflation",
    direction: "cooling",
    score: 72,
    explanation: "Core inflation is cooling gradually, but services remain sticky enough to keep policy risk alive.",
  },
  rates: {
    key: "rates",
    label: "Rates",
    direction: "stable",
    score: 58,
    explanation: "Policy rates are on hold, but the market is still debating how quickly cuts can start.",
  },
  centralBankSignals: {
    key: "centralBankSignals",
    label: "Central bank signals",
    direction: "elevated",
    score: 43,
    explanation: "Forward guidance is cautious and keeps policy uncertainty elevated around upcoming meetings.",
  },
  laborData: {
    key: "laborData",
    label: "Labor data",
    direction: "stable",
    score: 61,
    explanation: "Labor data is cooling from tight extremes without a clear break in employment quality.",
  },
  growthIndicators: {
    key: "growthIndicators",
    label: "Growth indicators",
    direction: "weakening",
    score: 46,
    explanation: "Manufacturing and consumer-sensitive readings are softening even as capex pockets stay resilient.",
  },
  recessionStress: {
    key: "recessionStress",
    label: "Recession/stress flags",
    direction: "elevated",
    score: 39,
    explanation: "Stress flags are not flashing crisis, but the growth cushion is thinner than headline indices imply.",
  },
  bondYields: {
    key: "bondYields",
    label: "Bond yields",
    direction: "rising",
    score: 44,
    explanation: "Long-end yields are drifting higher enough to pressure valuation-sensitive leadership if the move extends.",
  },
  usdEnvironment: {
    key: "usdEnvironment",
    label: "USD environment",
    direction: "easing",
    score: 67,
    explanation: "A softer USD is helping global liquidity and easing pressure on non-US cyclicals and commodities.",
  },
  summarySignals: [
    "inflation cooling",
    "yields rising",
    "growth weakening",
    "policy uncertainty elevated",
  ],
};

export const macroEvents: MacroEvent[] = [
  {
    id: "macro-1",
    title: "US CPI",
    region: "United States",
    date: "2026-03-18",
    severity: "Critical",
    severityScore: 92,
    category: "Inflation",
    consensus: "2.9% YoY",
    implication: "A softer print would extend support for duration-sensitive growth and reduce pressure on hedges.",
    watchFor: "Shelter and services disinflation breadth",
    explanation: "This release will decide whether the market can keep leaning into disinflation without repricing Fed timing.",
  },
  {
    id: "macro-2",
    title: "FOMC Rate Decision",
    region: "United States",
    date: "2026-03-20",
    severity: "Critical",
    severityScore: 95,
    category: "Central Bank",
    consensus: "Hold",
    implication: "The statement and dots matter more than the hold itself for yields, gold, and growth leadership.",
    watchFor: "Dot-plot median and chair tone on inflation persistence",
    explanation: "The meeting sets the policy narrative for the next several weeks across rates, USD, and leadership breadth.",
  },
  {
    id: "macro-3",
    title: "US Initial Claims and payroll revisions",
    region: "United States",
    date: "2026-03-21",
    severity: "High",
    severityScore: 76,
    category: "Labor",
    consensus: "Claims steady near cycle lows",
    implication: "A crack in labor resilience would amplify recession hedging and cool cyclical enthusiasm.",
    watchFor: "Breadth of softening across hiring and wage revisions",
    explanation: "Labor remains the main line between a soft landing and a sharper growth scare.",
  },
  {
    id: "macro-4",
    title: "China Credit Impulse",
    region: "China",
    date: "2026-03-22",
    severity: "High",
    severityScore: 74,
    category: "Liquidity",
    consensus: "Incremental easing",
    implication: "Confirmation would support industrial metals, cyclicals, and ex-US risk appetite.",
    watchFor: "Magnitude of new credit versus targeted easing promises",
    explanation: "This release matters for the durability of the global cyclical rebound and localization capex themes.",
  },
  {
    id: "macro-5",
    title: "Eurozone flash PMIs",
    region: "Europe",
    date: "2026-03-24",
    severity: "Moderate",
    severityScore: 63,
    category: "Growth",
    consensus: "Modest improvement",
    implication: "A better print would help industrial breadth, while a miss would reinforce defensive rotation pressure.",
    watchFor: "New orders versus services resilience",
    explanation: "The data will show whether growth weakening is broadening beyond isolated US-sensitive pockets.",
  },
  {
    id: "macro-6",
    title: "US 10Y auction and term-premium check",
    region: "United States",
    date: "2026-03-25",
    severity: "Moderate",
    severityScore: 61,
    category: "Bonds",
    consensus: "Stable demand",
    implication: "A weak auction would reinforce the yields-rising message and pressure long-duration equity multiples.",
    watchFor: "Indirect bid participation and tail size",
    explanation: "Bond-market tone is an underappreciated swing factor for factor leadership this month.",
  },
];

export const sectorHeatmap: SectorHeatmapItem[] = [
  { sector: "Semiconductors", performance1W: 3.8, performance1M: 8.1, regimeFit: 84 },
  { sector: "Industrials", performance1W: 2.1, performance1M: 4.9, regimeFit: 79 },
  { sector: "Precious Metals", performance1W: 1.8, performance1M: 5.2, regimeFit: 77 },
  { sector: "Software", performance1W: 1.6, performance1M: 4.1, regimeFit: 72 },
  { sector: "Clean Energy", performance1W: -1.4, performance1M: -2.2, regimeFit: 43 },
];

export const catalysts: CatalystItem[] = [
  {
    id: "cat-1",
    asset: "NVDA",
    title: "Cloud capex round-up",
    date: "2026-03-21",
    severity: "High",
    impact: "Positive demand read-through could extend semiconductor leadership if yields do not spike.",
  },
  {
    id: "cat-2",
    asset: "XLI",
    title: "US infrastructure procurement update",
    date: "2026-03-26",
    severity: "Moderate",
    impact: "Would support industrial breadth and confirm localization spending themes.",
  },
  {
    id: "cat-3",
    asset: "GLD",
    title: "Fed dots and real yields",
    date: "2026-03-20",
    severity: "Critical",
    impact: "Gold direction hinges on whether real yields stabilize despite policy uncertainty.",
  },
];
