import type { CatalystItem, MacroEvent, MacroState, SectorHeatmapItem } from "@/types";

export const macroState: MacroState = {
  asOf: "2026-03-14T09:00:00Z",
  inflation: {
    key: "inflation",
    label: "Inflation",
    direction: "cooling",
    score: 70,
    explanation: "Core inflation is cooling, but services and energy-sensitive inputs still keep policy risk active.",
  },
  rates: {
    key: "rates",
    label: "Rates",
    direction: "stable",
    score: 56,
    explanation: "Policy rates are on hold, but term premium and real-yield behavior still matter for factor leadership.",
  },
  centralBankSignals: {
    key: "centralBankSignals",
    label: "Central bank signals",
    direction: "elevated",
    score: 45,
    explanation: "The market still needs proof that the Fed can stay patient without reigniting a higher-for-longer scare.",
  },
  laborData: {
    key: "laborData",
    label: "Labor data",
    direction: "stable",
    score: 60,
    explanation: "Labor remains resilient enough to avoid a recession call, but no longer strong enough to be ignored.",
  },
  growthIndicators: {
    key: "growthIndicators",
    label: "Growth indicators",
    direction: "weakening",
    score: 48,
    explanation: "Manufacturing is soft while select capex and platform spending remain durable.",
  },
  recessionStress: {
    key: "recessionStress",
    label: "Recession/stress flags",
    direction: "elevated",
    score: 41,
    explanation: "Stress signals are contained, but softening breadth and rates sensitivity argue against complacency.",
  },
  bondYields: {
    key: "bondYields",
    label: "Bond yields",
    direction: "rising",
    score: 44,
    explanation: "Long-end yields drifting higher keep pressure on long-duration growth, crypto beta, and speculative add-ons.",
  },
  usdEnvironment: {
    key: "usdEnvironment",
    label: "USD environment",
    direction: "easing",
    score: 66,
    explanation: "A softer USD supports global liquidity, commodities, and international breadth at the margin.",
  },
  summarySignals: [
    "inflation cooling",
    "yields rising",
    "growth weakening",
    "policy uncertainty elevated",
  ],
};

export const macroEvents: MacroEvent[] = [
  {
    id: "macro-1",
    title: "US CPI",
    region: "United States",
    date: "2026-03-18",
    severity: "Critical",
    severityScore: 93,
    category: "Inflation",
    consensus: "2.9% YoY",
    implication: "A softer print would support duration-sensitive growth and reduce pressure on gold and bond hedges.",
    watchFor: "Services and shelter disinflation breadth",
    explanation: "This release is the main near-term arbiter of whether disinflation can keep carrying growth multiples.",
  },
  {
    id: "macro-2",
    title: "FOMC Rate Decision",
    region: "United States",
    date: "2026-03-20",
    severity: "Critical",
    severityScore: 96,
    category: "Central Bank",
    consensus: "Hold",
    implication: "The tone and dots matter more than the hold, especially for rates, crypto beta, and gold.",
    watchFor: "Dot plot, chair tone, and comments on services inflation",
    explanation: "A hawkish repricing would ripple through high-beta assets and concentrated AI leadership quickly.",
  },
  {
    id: "macro-3",
    title: "US Initial Claims",
    region: "United States",
    date: "2026-03-21",
    severity: "High",
    severityScore: 74,
    category: "Labor",
    consensus: "Stable near cycle lows",
    implication: "A softer labor print would reinforce the case for duration hedges and defensives.",
    watchFor: "Broadening softness instead of isolated claims noise",
    explanation: "Labor remains a key line between soft landing and growth scare narratives.",
  },
  {
    id: "macro-4",
    title: "China Credit Impulse",
    region: "China",
    date: "2026-03-22",
    severity: "High",
    severityScore: 73,
    category: "Liquidity",
    consensus: "Incremental easing",
    implication: "Would support industrials, metals, and global cyclical breadth if stronger than expected.",
    watchFor: "Magnitude of new credit versus rhetoric",
    explanation: "This release matters for the durability of localization and industrial capex themes.",
  },
  {
    id: "macro-5",
    title: "Eurozone Flash PMIs",
    region: "Europe",
    date: "2026-03-24",
    severity: "Moderate",
    severityScore: 62,
    category: "Growth",
    consensus: "Modest improvement",
    implication: "A better print would help industrial and value breadth, while a miss would support defensives.",
    watchFor: "New orders and manufacturing stabilization",
    explanation: "Europe-sensitive cyclicals need improving PMIs to keep up with US leadership.",
  },
  {
    id: "macro-6",
    title: "US 10Y Auction",
    region: "United States",
    date: "2026-03-25",
    severity: "Moderate",
    severityScore: 64,
    category: "Bonds",
    consensus: "Stable demand",
    implication: "A weak auction would pressure valuations and make duration hedges more valuable.",
    watchFor: "Tail size and indirect bids",
    explanation: "Bond market tone is a key underappreciated swing factor for this dashboard's leadership map.",
  },
  {
    id: "macro-7",
    title: "US Core PCE",
    region: "United States",
    date: "2026-03-28",
    severity: "High",
    severityScore: 79,
    category: "Inflation",
    consensus: "2.8% YoY",
    implication: "This can confirm or reverse the CPI read and reset the quarter-end rates narrative.",
    watchFor: "Monthly core print and revisions",
    explanation: "PCE confirmation matters for whether the market believes the disinflation trend is durable.",
  },
  {
    id: "macro-8",
    title: "US ISM Manufacturing",
    region: "United States",
    date: "2026-04-01",
    severity: "Moderate",
    severityScore: 66,
    category: "Growth",
    consensus: "Near breakeven",
    implication: "A firm print would help industrials and materials stay in the leadership mix.",
    watchFor: "New orders versus inventories",
    explanation: "This event matters for the cyclical sleeve and infrastructure-linked trade ideas.",
  },
];

export const sectorHeatmap: SectorHeatmapItem[] = [
  { sector: "Semiconductors", performance1W: 3.9, performance1M: 8.6, regimeFit: 85 },
  { sector: "Software", performance1W: 2.4, performance1M: 5.2, regimeFit: 78 },
  { sector: "Industrials", performance1W: 2.1, performance1M: 4.8, regimeFit: 80 },
  { sector: "Health Care", performance1W: 1.7, performance1M: 3.2, regimeFit: 75 },
  { sector: "Financials", performance1W: 1.4, performance1M: 2.9, regimeFit: 69 },
  { sector: "Energy", performance1W: 1.2, performance1M: 4.1, regimeFit: 71 },
  { sector: "Consumer Staples", performance1W: 0.8, performance1M: 2.3, regimeFit: 68 },
  { sector: "Crypto Proxy", performance1W: 4.5, performance1M: 11.3, regimeFit: 62 },
  { sector: "Clean Energy", performance1W: -1.6, performance1M: -3.1, regimeFit: 42 },
];

export const catalysts: CatalystItem[] = [
  {
    id: "cat-1",
    asset: "NVDA",
    title: "Cloud capex read-through",
    date: "2026-03-21",
    severity: "High",
    impact: "Positive demand checks would reinforce semiconductor leadership if yields do not spike.",
  },
  {
    id: "cat-2",
    asset: "XLI",
    title: "Infrastructure procurement update",
    date: "2026-03-26",
    severity: "Moderate",
    impact: "Would support industrial breadth and confirm localization and reshoring themes.",
  },
  {
    id: "cat-3",
    asset: "GLD",
    title: "Fed dots and real yields",
    date: "2026-03-20",
    severity: "Critical",
    impact: "Gold direction hinges on whether real yields roll over after the Fed.",
  },
  {
    id: "cat-4",
    asset: "USO",
    title: "OPEC+ compliance headlines",
    date: "2026-03-23",
    severity: "High",
    impact: "Could rapidly change the energy and inflation sleeve if supply discipline improves or breaks.",
  },
  {
    id: "cat-5",
    asset: "IBIT",
    title: "ETF flows and liquidity check",
    date: "2026-03-19",
    severity: "High",
    impact: "Crypto proxy demand stays constructive if flows hold through macro-event volatility.",
  },
];
