import type { JournalEntry } from "@/types";

export const journalEntries: JournalEntry[] = [
  {
    id: "jrnl-1",
    ticker: "MSFT",
    setupName: "Post-earnings continuation",
    setupTags: ["earnings", "quality-growth", "breakout"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-01-13T10:00:00.000Z",
    closedAt: "2026-01-29T10:00:00.000Z",
    entryPrice: 394,
    exitPrice: 421,
    thesis: "Stable yields plus AI spend momentum supported follow-through after earnings.",
    entryReasons: ["Leadership remained intact", "Earnings revision cycle improved", "Breakout was confirmed"],
    exitReasons: ["Target one hit", "Momentum started flattening"],
    rulesFollowed: true,
    plannedRiskPct: 0.9,
    plannedRiskAed: 11250,
    realizedPnlPct: 6.9,
    realizedPnlAed: 17640,
    outcomeR: 2.4,
    disciplineScore: 9,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "swing",
    reviewNotes: "Executed plan well and respected scale-out targets.",
  },
  {
    id: "jrnl-2",
    ticker: "ENPH",
    setupName: "Rate cut anticipation",
    setupTags: ["oversold", "macro", "rates"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-02T10:00:00.000Z",
    closedAt: "2026-02-14T10:00:00.000Z",
    entryPrice: 108,
    exitPrice: 101,
    thesis: "Expected oversold bounce into lower yields, but price never confirmed.",
    entryReasons: ["Macro thesis looked supportive", "Valuation was compressed"],
    exitReasons: ["Trend failed to improve", "Setup never confirmed"],
    rulesFollowed: false,
    plannedRiskPct: 1.2,
    plannedRiskAed: 15000,
    realizedPnlPct: -6.5,
    realizedPnlAed: -9720,
    outcomeR: -1.2,
    disciplineScore: 5,
    mistakeTag: "Entered before trigger",
    behaviorTags: ["oversized-trade", "rule-break"],
    holdingHorizon: "swing",
    reviewNotes: "Macro idea was reasonable, but execution ignored weak trend structure.",
  },
  {
    id: "jrnl-3",
    ticker: "GLD",
    setupName: "Fed hedge swing",
    setupTags: ["hedge", "macro", "gold"],
    direction: "LONG",
    status: "OPEN",
    openedAt: "2026-03-07T10:00:00.000Z",
    entryPrice: 204,
    thesis: "Wanted a defensive balance position ahead of CPI and Fed volatility.",
    entryReasons: ["Event density was elevated", "Real yields looked stretched"],
    exitReasons: [],
    rulesFollowed: true,
    plannedRiskPct: 0.8,
    plannedRiskAed: 10000,
    disciplineScore: 8,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "swing",
    reviewNotes: "Position size was correct; need patience into the event window.",
  },
  {
    id: "jrnl-4",
    ticker: "ASML",
    setupName: "Relative strength base breakout",
    setupTags: ["base-breakout", "semis", "rs"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-19T10:00:00.000Z",
    closedAt: "2026-03-05T10:00:00.000Z",
    entryPrice: 903,
    exitPrice: 949,
    thesis: "Semicap leadership broadened as capital spending expectations improved.",
    entryReasons: ["Relative strength improved", "Breakout confirmed", "Breadth supported semis"],
    exitReasons: ["Reached trailing target", "Wanted to reduce event exposure"],
    rulesFollowed: true,
    plannedRiskPct: 0.9,
    plannedRiskAed: 10800,
    realizedPnlPct: 5.1,
    realizedPnlAed: 11240,
    outcomeR: 1.9,
    disciplineScore: 8,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "position",
    reviewNotes: "Good patience on the entry. Could have pressed size a bit more.",
  },
  {
    id: "jrnl-5",
    ticker: "TSLA",
    setupName: "Countertrend reclaim",
    setupTags: ["countertrend", "high-beta", "failed"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-01-30T10:00:00.000Z",
    closedAt: "2026-02-04T10:00:00.000Z",
    entryPrice: 201,
    exitPrice: 196,
    thesis: "Expected a quick reclaim after a flush, but leadership never confirmed.",
    entryReasons: ["Sentiment was washed out", "Wanted a fast mean reversion"],
    exitReasons: ["Relative strength stayed weak", "Position lost trigger level"],
    rulesFollowed: false,
    plannedRiskPct: 1.1,
    plannedRiskAed: 13750,
    realizedPnlPct: -2.5,
    realizedPnlAed: -5150,
    outcomeR: -0.7,
    disciplineScore: 4,
    mistakeTag: "Chased weak tape",
    behaviorTags: ["early-exit", "rule-break"],
    holdingHorizon: "intraday",
    reviewNotes: "This did not deserve capital while better trends existed elsewhere.",
  },
  {
    id: "jrnl-6",
    ticker: "XLI",
    setupName: "Cyclical breadth continuation",
    setupTags: ["cyclicals", "etf", "trend"],
    direction: "LONG",
    status: "OPEN",
    openedAt: "2026-03-06T10:00:00.000Z",
    entryPrice: 128.5,
    thesis: "Preferred diversified cyclical exposure instead of adding more single-name tech beta.",
    entryReasons: ["Breadth broadened", "Localization theme remained active", "Valuation was cleaner than semis"],
    exitReasons: [],
    rulesFollowed: true,
    plannedRiskPct: 0.9,
    plannedRiskAed: 11250,
    disciplineScore: 8,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "position",
    reviewNotes: "Still valid, but needs protection if PMIs weaken further.",
  },
  {
    id: "jrnl-7",
    ticker: "SMCI",
    setupName: "High beta reclaim",
    setupTags: ["ai", "high-beta", "reclaim"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-24T10:00:00.000Z",
    closedAt: "2026-02-27T10:00:00.000Z",
    entryPrice: 892,
    exitPrice: 918,
    thesis: "Tactical reclaim worked, but I paid myself too fast.",
    entryReasons: ["Reclaimed key level", "Tape was risk-on", "Catalyst flow stayed strong"],
    exitReasons: ["Took profit early after first push"],
    rulesFollowed: false,
    plannedRiskPct: 0.8,
    plannedRiskAed: 9800,
    realizedPnlPct: 2.9,
    realizedPnlAed: 6840,
    outcomeR: 0.8,
    disciplineScore: 6,
    behaviorTags: ["early-exit"],
    holdingHorizon: "swing",
    reviewNotes: "Good read, but management was too defensive relative to the original plan.",
  },
  {
    id: "jrnl-8",
    ticker: "TLT",
    setupName: "Duration hedge",
    setupTags: ["hedge", "rates", "duration"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-01-18T10:00:00.000Z",
    closedAt: "2026-02-03T10:00:00.000Z",
    entryPrice: 94.2,
    exitPrice: 96.1,
    thesis: "Needed a duration hedge as growth data softened and policy timing looked less certain.",
    entryReasons: ["Yields looked extended", "Portfolio beta was elevated"],
    exitReasons: ["Hedge fulfilled its purpose", "Needed capital for cleaner ideas"],
    rulesFollowed: true,
    plannedRiskPct: 0.7,
    plannedRiskAed: 8750,
    realizedPnlPct: 2,
    realizedPnlAed: 5360,
    outcomeR: 1.3,
    disciplineScore: 8,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "swing",
    reviewNotes: "This improved portfolio balance and was exited for a valid reason.",
  },
  {
    id: "jrnl-9",
    ticker: "IBIT",
    setupName: "Liquidity beta breakout",
    setupTags: ["crypto", "beta", "breakout"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-10T10:00:00.000Z",
    closedAt: "2026-02-12T10:00:00.000Z",
    entryPrice: 35.2,
    exitPrice: 33.8,
    thesis: "Wanted to participate in crypto beta, but size drifted too high relative to setup quality.",
    entryReasons: ["Momentum was strong", "Liquidity was supportive"],
    exitReasons: ["Stop was missed intraday", "Recovered discipline too late"],
    rulesFollowed: false,
    plannedRiskPct: 1.4,
    plannedRiskAed: 17500,
    realizedPnlPct: -4,
    realizedPnlAed: -11120,
    outcomeR: -1.5,
    disciplineScore: 3,
    mistakeTag: "Missed stop",
    behaviorTags: ["oversized-trade", "missed-stop", "rule-break"],
    holdingHorizon: "intraday",
    reviewNotes: "This is the clearest example of risk drifting above process quality.",
  },
  {
    id: "jrnl-10",
    ticker: "JPM",
    setupName: "Quality financial breakout",
    setupTags: ["financials", "quality", "breakout"],
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-06T10:00:00.000Z",
    closedAt: "2026-02-20T10:00:00.000Z",
    entryPrice: 196,
    exitPrice: 205,
    thesis: "Wanted a higher-rate beneficiary with better quality than small-cap banks.",
    entryReasons: ["Bank breadth improved", "Rates backdrop helped NIM resilience"],
    exitReasons: ["Target reached", "Reallocated into semis"],
    rulesFollowed: true,
    plannedRiskPct: 0.8,
    plannedRiskAed: 9800,
    realizedPnlPct: 4.6,
    realizedPnlAed: 8940,
    outcomeR: 1.6,
    disciplineScore: 8,
    behaviorTags: ["followed-plan"],
    holdingHorizon: "position",
    reviewNotes: "Solid setup selection and clean exit execution.",
  },
];
