import type { JournalEntry } from "@/types";

export const journalEntries: JournalEntry[] = [
  {
    id: "jrnl-1",
    ticker: "MSFT",
    setupName: "Post-earnings continuation",
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-01-13",
    closedAt: "2026-01-29",
    entryPrice: 394,
    exitPrice: 421,
    thesis: "Stable yields plus AI spend momentum supported follow-through after earnings.",
    outcomeR: 2.4,
    disciplineScore: 9,
    reviewNotes: "Executed plan well and respected scale-out targets.",
  },
  {
    id: "jrnl-2",
    ticker: "ENPH",
    setupName: "Rate cut anticipation",
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-02",
    closedAt: "2026-02-14",
    entryPrice: 108,
    exitPrice: 101,
    thesis: "Expected oversold bounce into lower yields, but price never confirmed.",
    outcomeR: -1.2,
    disciplineScore: 6,
    mistakeTag: "Entered before trigger",
    reviewNotes: "Macro idea was reasonable, but execution ignored weak trend structure.",
  },
  {
    id: "jrnl-3",
    ticker: "GLD",
    setupName: "Fed hedge swing",
    direction: "LONG",
    status: "OPEN",
    openedAt: "2026-03-07",
    entryPrice: 204,
    thesis: "Wanted a defensive balance position ahead of CPI and Fed volatility.",
    disciplineScore: 8,
    reviewNotes: "Position size was correct; need patience into the event window.",
  },
  {
    id: "jrnl-4",
    ticker: "ASML",
    setupName: "Relative strength base breakout",
    direction: "LONG",
    status: "CLOSED",
    openedAt: "2026-02-19",
    closedAt: "2026-03-05",
    entryPrice: 903,
    exitPrice: 949,
    thesis: "Semicap leadership broadened as capital spending expectations improved.",
    outcomeR: 1.9,
    disciplineScore: 8,
    reviewNotes: "Good patience on the entry. Could have pressed size a bit more.",
  },
];
