import type { Holding, PortfolioWatchlistItem } from "@/types";

export const holdings: Holding[] = [
  {
    id: "hold-1",
    ticker: "MSFT",
    name: "Microsoft",
    assetClass: "Equity",
    sector: "Software",
    region: "United States",
    currency: "USD",
    themes: ["AI Infrastructure", "Quality Growth", "Cloud"],
    allocationBucket: "core",
    quantity: 95,
    avgCost: 401,
    marketPrice: 425,
    marketValueAed: 148200,
    unrealizedPnlAed: 8360,
    weightPct: 21.6,
    beta: 1.02,
    correlationTag: "US Mega Cap Tech",
    stopDistancePct: 6.5,
    openRiskAed: 9600,
  },
  {
    id: "hold-2",
    ticker: "ASML",
    name: "ASML Holding",
    assetClass: "Equity",
    sector: "Semiconductors",
    region: "Europe",
    currency: "EUR",
    themes: ["Semiconductor Leadership", "Localization", "Industrial Capex"],
    allocationBucket: "core",
    quantity: 18,
    avgCost: 890,
    marketPrice: 956,
    marketValueAed: 63100,
    unrealizedPnlAed: 4370,
    weightPct: 9.2,
    beta: 1.18,
    correlationTag: "Semiconductor Capex",
    stopDistancePct: 7.2,
    openRiskAed: 4540,
  },
  {
    id: "hold-3",
    ticker: "XLI",
    name: "Industrial Select Sector SPDR",
    assetClass: "ETF",
    sector: "Industrials",
    region: "United States",
    currency: "USD",
    themes: ["Global Cyclicals", "Infrastructure", "Localization"],
    allocationBucket: "core",
    quantity: 210,
    avgCost: 122,
    marketPrice: 129,
    marketValueAed: 99400,
    unrealizedPnlAed: 5390,
    weightPct: 14.5,
    beta: 0.97,
    correlationTag: "Global Cyclicals",
    stopDistancePct: 5.1,
    openRiskAed: 5070,
  },
  {
    id: "hold-4",
    ticker: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "ETF",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    themes: ["Gold", "Defensive Hedge", "Policy Uncertainty"],
    allocationBucket: "hedge",
    quantity: 120,
    avgCost: 199,
    marketPrice: 207,
    marketValueAed: 91100,
    unrealizedPnlAed: 3530,
    weightPct: 13.3,
    beta: 0.28,
    correlationTag: "Defensive Hedges",
    stopDistancePct: 4.2,
    openRiskAed: 3820,
  },
  {
    id: "hold-5",
    ticker: "ENPH",
    name: "Enphase Energy",
    assetClass: "Equity",
    sector: "Clean Energy",
    region: "United States",
    currency: "USD",
    themes: ["Rate Sensitive Growth", "Energy Transition", "Solar"],
    allocationBucket: "tactical",
    quantity: 150,
    avgCost: 106,
    marketPrice: 99,
    marketValueAed: 54500,
    unrealizedPnlAed: -3850,
    weightPct: 8,
    beta: 1.44,
    correlationTag: "Rate Sensitive Growth",
    stopDistancePct: 8.5,
    openRiskAed: 4630,
  },
];

export const watchlist: PortfolioWatchlistItem[] = [
  {
    id: "watch-1",
    ticker: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    sector: "Semiconductors",
    region: "United States",
    currency: "USD",
    themes: ["AI Infrastructure", "Semiconductor Leadership", "US Growth"],
    priority: "High",
    targetEntry: "958-972",
    thesis: "Leadership quality remains elite if CPI and yields cooperate.",
    candidateAllocationPct: 4.5,
    candidateBucket: "tactical",
  },
  {
    id: "watch-2",
    ticker: "SMCI",
    name: "Super Micro Computer",
    assetClass: "Equity",
    sector: "Servers",
    region: "United States",
    currency: "USD",
    themes: ["AI Infrastructure", "High Beta"],
    priority: "Medium",
    targetEntry: "886-920",
    thesis: "Only valid on confirmed reclaim because volatility quality remains poor.",
    candidateAllocationPct: 2.5,
    candidateBucket: "tactical",
  },
  {
    id: "watch-3",
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    assetClass: "ETF",
    sector: "Rates",
    region: "United States",
    currency: "USD",
    themes: ["Duration Hedge", "Policy Uncertainty"],
    priority: "Medium",
    targetEntry: "Above 95.5 on yield rollover",
    thesis: "Useful hedge if growth weakens faster than inflation re-accelerates.",
    candidateAllocationPct: 4,
    candidateBucket: "hedge",
  },
  {
    id: "watch-4",
    ticker: "TSLA",
    name: "Tesla",
    assetClass: "Equity",
    sector: "Autos",
    region: "United States",
    currency: "USD",
    themes: ["EV Transition", "Rate Sensitive Growth", "China Exposure"],
    priority: "Low",
    targetEntry: "Reclaim 198 with RS improvement",
    thesis: "Needs trend repair before it can compete for capital with cleaner setups.",
    candidateAllocationPct: 1.5,
    candidateBucket: "tactical",
  },
];
