import type { Holding, PortfolioWatchlistItem } from "@/types";

export const holdings: Holding[] = [
  {
    id: "hold-1",
    ticker: "MSFT",
    name: "Microsoft",
    assetClass: "Equity",
    sector: "Software",
    region: "United States",
    currency: "USD",
    themes: ["AI Infrastructure", "Quality Growth", "Cloud"],
    allocationBucket: "core",
    quantity: 140,
    avgCost: 401,
    marketPrice: 427,
    marketValueAed: 219000,
    unrealizedPnlAed: 13350,
    weightPct: 17.5,
    beta: 0.98,
    correlationTag: "AI Leadership",
    stopDistancePct: 5.2,
    openRiskAed: 11400,
  },
  {
    id: "hold-2",
    ticker: "NVDA",
    name: "NVIDIA",
    assetClass: "Equity",
    sector: "Semiconductors",
    region: "United States",
    currency: "USD",
    themes: ["AI Infrastructure", "Semiconductor Leadership", "US Growth"],
    allocationBucket: "core",
    quantity: 34,
    avgCost: 883,
    marketPrice: 968,
    marketValueAed: 120400,
    unrealizedPnlAed: 10680,
    weightPct: 9.6,
    beta: 1.32,
    correlationTag: "AI Leadership",
    stopDistancePct: 5.6,
    openRiskAed: 9300,
  },
  {
    id: "hold-3",
    ticker: "XLI",
    name: "Industrial Select Sector SPDR",
    assetClass: "ETF",
    sector: "Industrials",
    region: "United States",
    currency: "USD",
    themes: ["Global Cyclicals", "Infrastructure", "Localization"],
    allocationBucket: "core",
    quantity: 390,
    avgCost: 123,
    marketPrice: 131,
    marketValueAed: 187600,
    unrealizedPnlAed: 11480,
    weightPct: 15,
    beta: 0.94,
    correlationTag: "Cyclical Breadth",
    stopDistancePct: 4.4,
    openRiskAed: 7420,
  },
  {
    id: "hold-4",
    ticker: "GLD",
    name: "SPDR Gold Shares",
    assetClass: "ETF",
    sector: "Precious Metals",
    region: "Global",
    currency: "USD",
    themes: ["Gold", "Defensive Hedge", "Policy Uncertainty"],
    allocationBucket: "hedge",
    quantity: 210,
    avgCost: 200,
    marketPrice: 208,
    marketValueAed: 160900,
    unrealizedPnlAed: 7230,
    weightPct: 12.9,
    beta: 0.26,
    correlationTag: "Defensive Hedges",
    stopDistancePct: 3.5,
    openRiskAed: 5630,
  },
  {
    id: "hold-5",
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    assetClass: "ETF",
    sector: "Rates",
    region: "United States",
    currency: "USD",
    themes: ["Duration Hedge", "Policy Uncertainty", "Rate Relief"],
    allocationBucket: "hedge",
    quantity: 520,
    avgCost: 95,
    marketPrice: 96,
    marketValueAed: 183400,
    unrealizedPnlAed: 4120,
    weightPct: 14.7,
    beta: -0.18,
    correlationTag: "Defensive Hedges",
    stopDistancePct: 4.1,
    openRiskAed: 5910,
  },
  {
    id: "hold-6",
    ticker: "XOM",
    name: "Exxon Mobil",
    assetClass: "Equity",
    sector: "Energy",
    region: "United States",
    currency: "USD",
    themes: ["Energy Cash Flow", "Inflation Protection", "Value"],
    allocationBucket: "core",
    quantity: 180,
    avgCost: 112,
    marketPrice: 118,
    marketValueAed: 78000,
    unrealizedPnlAed: 3960,
    weightPct: 6.2,
    beta: 0.82,
    correlationTag: "Energy Inflation",
    stopDistancePct: 4.8,
    openRiskAed: 3120,
  },
  {
    id: "hold-7",
    ticker: "XLV",
    name: "Health Care Select Sector SPDR",
    assetClass: "ETF",
    sector: "Health Care",
    region: "United States",
    currency: "USD",
    themes: ["Defensive Growth", "Quality", "Earnings Stability"],
    allocationBucket: "core",
    quantity: 240,
    avgCost: 138,
    marketPrice: 141,
    marketValueAed: 124200,
    unrealizedPnlAed: 2670,
    weightPct: 9.9,
    beta: 0.62,
    correlationTag: "Defensive Quality",
    stopDistancePct: 4,
    openRiskAed: 3980,
  },
  {
    id: "hold-8",
    ticker: "IBIT",
    name: "iShares Bitcoin Trust",
    assetClass: "ETF",
    sector: "Crypto Proxy",
    region: "United States",
    currency: "USD",
    themes: ["Crypto Proxy", "Alternative Beta", "Liquidity"],
    allocationBucket: "tactical",
    quantity: 470,
    avgCost: 37,
    marketPrice: 41,
    marketValueAed: 70300,
    unrealizedPnlAed: 6870,
    weightPct: 5.6,
    beta: 1.68,
    correlationTag: "AI Leadership",
    stopDistancePct: 8.2,
    openRiskAed: 5120,
  },
];

export const watchlist: PortfolioWatchlistItem[] = [
  {
    id: "watch-1",
    ticker: "AMZN",
    name: "Amazon",
    assetClass: "Equity",
    sector: "Internet",
    region: "United States",
    currency: "USD",
    themes: ["Consumer Cloud", "AI Infrastructure", "US Growth"],
    priority: "High",
    targetEntry: "Above 191 on follow-through",
    thesis: "Cloud and retail execution remain supportive if rates do not reprice higher.",
    candidateAllocationPct: 3.5,
    candidateBucket: "core",
  },
  {
    id: "watch-2",
    ticker: "SMH",
    name: "VanEck Semiconductor ETF",
    assetClass: "ETF",
    sector: "Semiconductors",
    region: "United States",
    currency: "USD",
    themes: ["Semiconductor Leadership", "AI Infrastructure", "US Growth"],
    priority: "High",
    targetEntry: "Reclaim 255 with breadth confirmation",
    thesis: "Broader semi participation is cleaner than chasing single-name gaps at extended levels.",
    candidateAllocationPct: 4,
    candidateBucket: "tactical",
  },
  {
    id: "watch-3",
    ticker: "META",
    name: "Meta Platforms",
    assetClass: "Equity",
    sector: "Internet",
    region: "United States",
    currency: "USD",
    themes: ["Advertising Recovery", "AI Enablement", "Quality Growth"],
    priority: "Medium",
    targetEntry: "Break and hold above 528",
    thesis: "Meta remains a quality compounder if ad momentum and capex discipline stay intact.",
    candidateAllocationPct: 2.5,
    candidateBucket: "core",
  },
  {
    id: "watch-4",
    ticker: "XLE",
    name: "Energy Select Sector SPDR",
    assetClass: "ETF",
    sector: "Energy",
    region: "United States",
    currency: "USD",
    themes: ["Energy Cash Flow", "Inflation Protection", "Commodity Beta"],
    priority: "Medium",
    targetEntry: "122-124 on oil bid confirmation",
    thesis: "Energy works as an inflation hedge if geopolitics and supply discipline keep crude firm.",
    candidateAllocationPct: 3,
    candidateBucket: "core",
  },
  {
    id: "watch-5",
    ticker: "USO",
    name: "United States Oil Fund",
    assetClass: "ETF",
    sector: "Energy Proxy",
    region: "Global",
    currency: "USD",
    themes: ["Energy Proxy", "Commodity Beta", "Inflation Protection"],
    priority: "Low",
    targetEntry: "Above 81 only",
    thesis: "Pure oil beta is useful only if the tape transitions into a stronger inflation scare regime.",
    candidateAllocationPct: 1.5,
    candidateBucket: "tactical",
  },
  {
    id: "watch-6",
    ticker: "IBIT",
    name: "iShares Bitcoin Trust",
    assetClass: "ETF",
    sector: "Crypto Proxy",
    region: "United States",
    currency: "USD",
    themes: ["Crypto Proxy", "Alternative Beta", "Liquidity"],
    priority: "Medium",
    targetEntry: "Above 42 after pullback hold",
    thesis: "Crypto beta remains workable, but only if yields stabilize and risk appetite stays broad.",
    candidateAllocationPct: 1.8,
    candidateBucket: "tactical",
  },
  {
    id: "watch-7",
    ticker: "JPM",
    name: "JPMorgan Chase",
    assetClass: "Equity",
    sector: "Financials",
    region: "United States",
    currency: "USD",
    themes: ["Quality Financials", "Higher Rates", "US Large Cap"],
    priority: "Medium",
    targetEntry: "Above 205 after bank breadth confirms",
    thesis: "JPM is a cleaner expression of stable growth plus higher-rate resilience than lower-quality regional names.",
    candidateAllocationPct: 2.5,
    candidateBucket: "core",
  },
  {
    id: "watch-8",
    ticker: "TSLA",
    name: "Tesla",
    assetClass: "Equity",
    sector: "Autos",
    region: "United States",
    currency: "USD",
    themes: ["EV Transition", "Rate Sensitive Growth", "China Exposure"],
    priority: "Low",
    targetEntry: "Only above 198 with RS repair",
    thesis: "Still too messy versus cleaner leadership and should remain a low-priority watch item.",
    candidateAllocationPct: 1,
    candidateBucket: "tactical",
  },
];
