import type { Holding } from "@/types";

export const holdings: Holding[] = [
  {
    id: "hold-1",
    ticker: "MSFT",
    name: "Microsoft",
    sector: "Software",
    region: "United States",
    quantity: 95,
    avgCost: 401,
    marketPrice: 425,
    marketValueAed: 148200,
    unrealizedPnlAed: 8360,
    weightPct: 21.6,
    beta: 1.02,
    correlationTag: "US Mega Cap Tech",
    stopDistancePct: 6.5,
    openRiskAed: 9600,
  },
  {
    id: "hold-2",
    ticker: "ASML",
    name: "ASML Holding",
    sector: "Semiconductors",
    region: "Europe",
    quantity: 18,
    avgCost: 890,
    marketPrice: 956,
    marketValueAed: 63100,
    unrealizedPnlAed: 4370,
    weightPct: 9.2,
    beta: 1.18,
    correlationTag: "Semiconductor Capex",
    stopDistancePct: 7.2,
    openRiskAed: 4540,
  },
  {
    id: "hold-3",
    ticker: "XLI",
    name: "Industrial Select Sector SPDR",
    sector: "Industrials",
    region: "United States",
    quantity: 210,
    avgCost: 122,
    marketPrice: 129,
    marketValueAed: 99400,
    unrealizedPnlAed: 5390,
    weightPct: 14.5,
    beta: 0.97,
    correlationTag: "Global Cyclicals",
    stopDistancePct: 5.1,
    openRiskAed: 5070,
  },
  {
    id: "hold-4",
    ticker: "GLD",
    name: "SPDR Gold Shares",
    sector: "Precious Metals",
    region: "Global",
    quantity: 120,
    avgCost: 199,
    marketPrice: 207,
    marketValueAed: 91100,
    unrealizedPnlAed: 3530,
    weightPct: 13.3,
    beta: 0.28,
    correlationTag: "Defensive Hedges",
    stopDistancePct: 4.2,
    openRiskAed: 3820,
  },
  {
    id: "hold-5",
    ticker: "ENPH",
    name: "Enphase Energy",
    sector: "Clean Energy",
    region: "United States",
    quantity: 150,
    avgCost: 106,
    marketPrice: 99,
    marketValueAed: 54500,
    unrealizedPnlAed: -3850,
    weightPct: 8,
    beta: 1.44,
    correlationTag: "Rate Sensitive Growth",
    stopDistancePct: 8.5,
    openRiskAed: 4630,
  },
];
